channels:
  - defaults
dependencies:
  - numpy>=1.4.1
  - pip>=20.3.3
  - python=3.8
  - pip:
      - matplotlib>=3.3.3
      - legwork
      - pandas
      - astropy
      - h5py 
      - tables
      - schwimmbad
